release:

before:
  hooks:
    - go mod tidy

builds:
  - id: gqldoc
    main: ./cmd/gqldoc/main.go
    binary: gqldoc
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm
        goarm: 7

archives:
- builds:
  - gqldoc
  name_template: 'gqldoc_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip

brews:
- name: gqldoc
  tap:
    owner: Code-Hex
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/Code-Hex/gqldoc"
  description: "The easiest way to make documents for GraphQL"
  folder: Formula
  install: |
    bin.install "gqldoc"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch