name: doc
on:
  pull_request: {}
jobs:
  update-doc:
    runs-on: ubuntu-latest
    env:
      GITHUB_TARGET_SCHEMA: example/github/schema.graphql
      SHOPIFY_TARGET_SCHEMA: example/shopify/schema.graphql
      STARWARS_TARGET_SCHEMA: example/starwars/schema.graphql
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub GraphQL Document
        uses: Code-Hex/gqldoc-actions@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: ${{ env.GITHUB_TARGET_SCHEMA }}
          output: example/github
      - name: Generate Shopify GraphQL Document
        uses: Code-Hex/gqldoc-actions@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: ${{ env.SHOPIFY_TARGET_SCHEMA }}
          output: example/shopify
      - name: Generate Starwars GraphQL Document
        uses: Code-Hex/gqldoc-actions@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          schema: ${{ env.STARWARS_TARGET_SCHEMA }}
          output: example/starwars